### ISSUE TITLE
 fabric_network_ids attribute of the vra_network_ip_range resource doesn’t link any NSX-T segment to the IP range 

### ISSUE THREAD

**Issue by vmeoc** [vmware/terraform-provider-vra#501]
### vRA Version

                vRA 8.10.2

 

### Terraform Version

                Terraform v1.3.3

 

### vRA Terraform Provider Version

                vRA provider version 0.7.3 (but probably starts from 0.6.0 where the change on the resource attribute was implemented.

 

### Affected Resource(s)

 

```hcl

resource "vra_network_ip_range" "xxxxxxxx" {

  name              = “xxxxxxxx"

  description       = “xxxxxxxx"

  start_ip_address  = "00.00.00.00"

  end_ip_address    = "00.00.00.00"

  ip_version        = "IPv4"

  fabric_network_ids = [data.vra_fabric_network.yyyyyyyyyy.id]

}

```

 

### Expected Behavior

                The provided list with only on segment should have linked it to the IP range created, just like in provider version 0.5.3 was doing with a string

 

### Actual Behavior

                Terraform apply is successful with no error or warning, but the IP range is not connected to any NSX-T segment anymore

 

### Steps to Reproduce

`terraform apply` with the configuration (on an already existing resource)

 

### Screenshots

N/A

 

### Debug Output

N/A

 

### Panic Output

                N/A

 

### Important Factoids

                N/A

 

### References

                N/A

 

 

### Community Note

 

* Please vote on this issue by adding a 👍 [reaction]([https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/] to the original issue to help the community and maintainers prioritize this request

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request

* If you are interested in working on this issue or have submitted a pull request, please leave a comment

 

### Code of Conduct

This project has a Code of Conduct that all participants are expected to understand and follow:
* [ ] I have read and agree to the project's [Code of Conduct](https://github.com/vmware/terraform-provider-vra/blob/main/CODE-OF-CONDUCT.md)

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here.
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by frodenas** [comment]
This has been solved as part of #504.

**Comment by vmeoc** [comment]
Hi,
my customer tells me that the latest release did not fix the issue: when fabric_network_ids is being used instead of fabric_network_id, no fabric network are attached to the ip range.
